(in-package "ACL2")
(include-book "doublecheck" :dir :teachpacks)
(include-book "rand" :dir :teachpacks)

(defun maximum (xs)
  (if (consp (cdr xs))
      (let ((max (maximum (cdr xs))))
        (if (> (car xs) max)
            (car xs)
            max))
      (car xs)))

(defun minimum (xs)
  (if (consp (cdr xs))
      (let ((min (minimum (cdr xs))))
        (if (< (car xs) min)
            (car xs)
            min))
      (car xs)))
